name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'node'
      - run: yarn install
      - run: yarn lint
      - run: yarn format
